export const BUILDING_TYPES = {
  LIBRARY: 'LIBRARY',
  RESIDENCE_HALL: 'RESIDENCE HALL',
  INSTRUCTIONAL: 'INSTRUCTIONAL',
  RESEARCH: 'RESEARCH',
  ADMINISTRATIVE: 'ADMINISTRATIVE',
  DINING_COURT: 'DINING COURT',
  CULTURAL_CENTER: 'CULTURAL CENTER',
  MISC: 'MISC',
}

export const ROOM_TYPES = {
  CLASSROOM: 'CLASSROOM',
  LAB: 'LAB',
  BATHROOM: 'BATHROOM',
  MISC: 'MISC',
}
