export const BUILDING_TYPES = {
  LIBRARY: 'LIBRARY',
  RESIDENCE_HALL: 'RESIDENCE HALL',
  INSTRUCTIONAL: 'INSTRUCTIONAL',
  RESEARCH: 'RESEARCH',
  ADMINISTRATIVE: "ADMINISTRATIVE",
  DINING_COURT: 'DINING COURT'
  MISC: 'MISC',
}

export const ROOM_TYPES = {
  CLASSROOM: 'CLASSROOM',
  LAB: 'LAB',
  BATHROOM: 'BATHROOM',
  MISC: 'MISC',
}
